server:
  port: 8084




#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true

#    local:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: 123456
#      url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
#
#    ucp:
#      driver-class-name: oracle.jdbc.OracleDriver
#      username: ucpcenter
#      password: ucpcenter
#      url: oracle:thin:@192.168.30.76:1521:ucpdc
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
